M48
; DRILL file {KiCad 8.0.3} date 2024-07-04T14:19:14-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-04T14:19:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.5358Y-3.5369
X5.7634Y-3.5369
T2
X3.7369Y-4.7982
X7.86Y-3.7126
M30
