M48
; DRILL file {KiCad 7.0.7} date Sat 19 Aug 2023 05:10:08 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-19T17:10:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X43.5Y-61.3
X43.5Y-115.3
X139.5Y-61.3
X139.5Y-115.3
T2
X131.3Y-61.562
T0
M30
