M48
; DRILL file {KiCad 7.0.7} date Wed 27 Sep 2023 06:03:21 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-27T18:03:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X6.8394Y-4.1996
X6.8394Y-6.3256
X10.6189Y-4.1996
X10.6189Y-6.3256
T2
X10.2961Y-4.2099
T0
M30
